# Site settings
title: "The Golden Ledger: Wisdom from the Halls of Commerce"
tagline: Insights on Corporate Finance, Business Strategy and Data Analyics
description: > 
  A blog dedicated to sharing my learnings and research insights
  in corporate finance, business strategy and data analytics.
baseurl: ""
url: ""
github_username:  abinabraham23
linkedin_username: abinabraham23

# Author settings
author:
  name: Abin Abraham
  email: abinabrahamreal@gmail.com
  bio: Management student and continuous learner, passionate about all things Technology. Exploring corporate finance, business strategy and data analytics.
  avatar: /images/profile.jpg
  social_links:
    linkedin: https://linkedin.com/in/abinabraham23
    github: https://github.com/abinabraham23

# Build settings
markdown: kramdown

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Excerpt settings
excerpt_separator: <!--more-->

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Empty plugins array to ensure no feed plugin is loaded
plugins: []  